language: node_js
node_js:
  - 8
branchs:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - cnpm install
scripts:
  - npm build
