language: node_js
node_js:
  - 8
branchs:
  only:
    - master
addons:
  ssh_known_hosts:
    - 47.106.87.3
before_install:
  - openssl aes-256-cbc -K $encrypted_0ec4f66d4059_key -iv $encrypted_0ec4f66d4059_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  # 开启 ssh-agent，即允许使用 ssh 命令
  - eval "$(ssh-agent -s)"
  # 给予 id_rsa 文件权限，避免警告
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 47.106.87.3\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # 将私钥添加到 ssh
  - ssh-add ~/.ssh/id_rsa
script:
  - npm run test
after_success:
  - npm prune --production # 删除devDependencies
  - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - cnpm i
  - npm run build
  - tar -zcvf build.tar.gz build
  - scp build.tar.gz root@47.106.87.3:/home/root/TodoList
  - ssh root@47.106.87.3 'cd /home/root/TodoList && tar -zxvf build.tar.gz'
  - ssh root@47.106.87.3 'pm2 restart TodoList'
